#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Diff
version:      0.56
version_from: 
installdirs:  site
requires:
    Algorithm::Diff:               1.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
