---
abstract: unknown
author:
  - unknown
build_requires:
  Data::Dumper: 0
  ExtUtils::MakeMaker: 0
  Getopt::Long: 0.88
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.3
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Diff
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Diff: 1.15
  Exporter: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=HTML-Diff
  repository: git://github.com/neilbowers/html-diff.git
version: 0.58
